/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app/theme.ts
 * Command: astryx theme build app/theme.ts --out app/theme.css
 * CLI: @astryxdesign/cli@0.5.3
 * Core: @astryxdesign/core@0.5.3
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface HeadingTypeMap {
    'display-1': true;
    'display-2': true;
    'display-3': true;
  }
}
