/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app/theme.ts
 * Command: astryx theme build app/theme.ts --out app/theme.css
 * CLI: @astryxdesign/cli@0.5.3
 * Core: @astryxdesign/core@0.5.3
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const devopsTrackerTheme: DefinedTheme;
