/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app/theme.ts
 * Command: astryx theme build app/theme.ts --out app/theme.css
 * CLI: @astryxdesign/cli@0.5.3
 * Core: @astryxdesign/core@0.5.3
 */

/**
 * devops-tracker theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { devopsTrackerTheme } from './devops-tracker';
 *   import './devops-tracker.css';
 */
export const devopsTrackerTheme = {
  name: 'devops-tracker',
  __built: true,
  tokens: {
    "--color-accent": "light-dark(#0061B1, #97CBFF)",
    "--color-accent-muted": "light-dark(color-mix(in srgb, var(--color-accent) 20%, transparent), color-mix(in srgb, var(--color-accent) 25%, transparent))",
    "--color-on-accent": "light-dark(#FFFFFF, #003562)",
    "--color-neutral": "light-dark(#191C221A, #DDE3EC33)",
    "--color-background-surface": "light-dark(#FAFCFF, #171C22)",
    "--color-background-body": "light-dark(#EDF1FA, #0B1118)",
    "--color-overlay": "light-dark(#191C2266, #171C2299)",
    "--color-overlay-hover": "light-dark(#191C220D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#191C221A, #FFFFFF1A)",
    "--color-background-muted": "light-dark(#191C220D, #171C2280)",
    "--color-text-primary": "light-dark(#191C22, #DDE3EC)",
    "--color-text-secondary": "light-dark(#414753, #A2ACB9)",
    "--color-text-disabled": "light-dark(#8B919E, #565F6B)",
    "--color-text-accent": "var(--color-accent)",
    "--color-icon-accent": "var(--color-accent)",
    "--color-icon-primary": "light-dark(#191C22, #DDE3EC)",
    "--color-icon-secondary": "light-dark(#414753, #A2ACB9)",
    "--color-icon-disabled": "light-dark(#8B919E, #565F6B)",
    "--color-background-card": "light-dark(#FAFCFF, #171C22)",
    "--color-background-popover": "light-dark(#FAFCFF, #2C3137)",
    "--color-background-inverted": "light-dark(#191C22, #F9FCFF)",
    "--color-border": "light-dark(#191C221A, #EBF1FA1A)",
    "--color-border-emphasized": "light-dark(#8B919E, #5F6975)",
    "--color-skeleton": "light-dark(#A5ABB9, #3E4853)",
    "--color-track": "light-dark(#A5ABB9, #3E4853)",
    "--color-shadow": "light-dark(#0000001A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--radius-none": "0px",
    "--radius-inner": "4px",
    "--radius-element": "8px",
    "--radius-container": "12px",
    "--radius-page": "16px",
    "--radius-chat": "16px",
    "--radius-full": "9999px"
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },

};
