export interface SlashCommandItem {
  cmd: string;
  name: string;
  desc: string;
  category: string;
  aliases: string[];
  color: string;
  badge: string;
}

export const SLASH_CATEGORIES = [
  { id: "all", label: "Tất cả lệnh (16)" },
  { id: "coordination", label: "⚡ Điều phối & Giao việc (/assign, /log...)" },
  { id: "resource", label: "📊 Nguồn lực & Tải (/free, /overload...)" },
  { id: "detail", label: "🔍 Chi tiết (/info, /task, /project)" },
  { id: "report", label: "🚨 Báo cáo & Cảnh báo (/report, /overdue)" },
  { id: "basic", label: "⚙️ Lệnh cơ bản (/help, /members...)" },
];

export const SLASH_COMMANDS_LIST: SlashCommandItem[] = [
  {
    cmd: "/assign",
    name: "Gán task cho thành viên",
    desc: "Mở Form Modal điền mẫu: Tên task, nhân sự, dự án, thời lượng & hạn chót.",
    category: "coordination",
    aliases: ["/giaoviet", "/add-task"],
    color: "text-sky-400",
    badge: "Giao việc",
  },
  {
    cmd: "/reassign",
    name: "Chuyển task nhân sự",
    desc: "Chuyển giao task từ thành viên này sang thành viên khác kèm cập nhật effort.",
    category: "coordination",
    aliases: ["/chuyentask", "/doinguoi", "/transfer"],
    color: "text-indigo-400",
    badge: "Điều phối",
  },
  {
    cmd: "/add",
    name: "Thêm task / Lập kế hoạch",
    desc: "Lập kế hoạch task mới và dự kiến thời lượng triển khai trong tương lai.",
    category: "coordination",
    aliases: ["/plan", "/taotask", "/kehoach"],
    color: "text-blue-400",
    badge: "Kế hoạch",
  },
  {
    cmd: "/log",
    name: "Ghi nhận công việc (Log)",
    desc: "Ghi nhận task đang làm hoặc vừa hoàn thành kèm số giờ thực tế.",
    category: "coordination",
    aliases: ["/work", "/done", "/ghilog"],
    color: "text-cyan-400",
    badge: "Ghi log",
  },
  {
    cmd: "/remove",
    name: "Xóa task khỏi danh sách",
    desc: "Xóa hoặc hủy bỏ một task đã hủy/không cần triển khai khỏi hệ thống.",
    category: "coordination",
    aliases: ["/xoatask", "/delete-task", "/huytask"],
    color: "text-rose-400",
    badge: "Xóa task",
  },
  {
    cmd: "/free",
    name: "Thành viên đang rảnh",
    desc: "Truy vấn tức thì danh sách kỹ sư đang trống việc (< 288m) để giao việc gấp.",
    category: "resource",
    aliases: ["/available", "/ranh", "/nhansuranh"],
    color: "text-emerald-400",
    badge: "Nguồn lực",
  },
  {
    cmd: "/overload",
    name: "Thành viên quá tải",
    desc: "Cảnh báo các kỹ sư có tải công việc vượt định mức an toàn (> 480m/ngày).",
    category: "resource",
    aliases: ["/overloaded", "/quatai", "/busy"],
    color: "text-rose-400",
    badge: "Nguồn lực",
  },
  {
    cmd: "/effort",
    name: "Tổng % Effort đội ngũ",
    desc: "Tổng hợp phân bổ effort và thời lượng công việc của toàn bộ kỹ sư.",
    category: "resource",
    aliases: ["/my-effort", "/taicongviec", "/totaleffort"],
    color: "text-violet-400",
    badge: "Nguồn lực",
  },
  {
    cmd: "/load",
    name: "Tình trạng tải công việc",
    desc: "Hiển thị tình trạng tải công việc tổng thể và mức độ bận rộn của các thành viên.",
    category: "resource",
    aliases: ["/workload", "/bandwidth", "/tinhtrangtai"],
    color: "text-amber-400",
    badge: "Nguồn lực",
  },
  {
    cmd: "/info",
    name: "Thông tin thành viên",
    desc: "Tra cứu task đang làm và kế hoạch: /info [Tên thành viên].",
    category: "detail",
    aliases: ["/status", "/thanhvien", "/member-info"],
    color: "text-sky-300",
    badge: "Chi tiết",
  },
  {
    cmd: "/task",
    name: "Thông tin chi tiết task",
    desc: "Hiển thị chi tiết tiến độ, người phụ trách của task: /task [Tên task].",
    category: "detail",
    aliases: ["/task-info", "/chitiettask"],
    color: "text-cyan-300",
    badge: "Chi tiết",
  },
  {
    cmd: "/project",
    name: "Thông tin chi tiết dự án",
    desc: "Tra cứu tiến độ, danh sách task và tổng effort: /project [Tên dự án].",
    category: "detail",
    aliases: ["/project-info", "/chitietduan"],
    color: "text-purple-400",
    badge: "Chi tiết",
  },
  {
    cmd: "/report",
    name: "Báo cáo phân bổ Effort",
    desc: "Tổng hợp phân bổ Effort theo từng dự án và tiến độ hiện tại.",
    category: "report",
    aliases: ["/baocao", "/summary", "/phanbo"],
    color: "text-teal-400",
    badge: "Báo cáo",
  },
  {
    cmd: "/overdue",
    name: "Task trễ hạn / Gấp",
    desc: "Quét và tổng hợp toàn bộ các task bị quá hạn hoặc cận kề deadline.",
    category: "report",
    aliases: ["/trehan", "/deadline", "/gap"],
    color: "text-amber-400",
    badge: "Cảnh báo",
  },
  {
    cmd: "/tasks",
    name: "Danh sách công việc",
    desc: "Hiển thị toàn bộ danh sách task đang thực hiện và kế hoạch sắp tới.",
    category: "basic",
    aliases: ["/all-tasks", "/danhsachtask", "/viec"],
    color: "text-sky-400",
    badge: "Cơ bản",
  },
  {
    cmd: "/members",
    name: "Danh sách thành viên",
    desc: "Hiển thị danh sách toàn bộ thành viên trong đội ngũ, chuyên môn và trạng thái.",
    category: "basic",
    aliases: ["/member", "/nhansu", "/team"],
    color: "text-emerald-400",
    badge: "Cơ bản",
  },
  {
    cmd: "/help",
    name: "Hướng dẫn & Trợ giúp",
    desc: "Hiển thị hướng dẫn chi tiết các lệnh slash (/) và cách dùng AI Assistant.",
    category: "basic",
    aliases: ["/huongdan", "/?"],
    color: "text-neutral-300",
    badge: "Trợ giúp",
  },
];

export const TECH_STACK_ITEMS = [
  {
    idx: "01",
    title: "Next.js 15 App Router",
    desc: "React 19, Server Components & Streaming SSR giúp tải trang tức thì và tối ưu SEO vượt trội.",
    color: "text-sky-400",
    bg: "bg-sky-500/15",
    border: "hover:border-sky-500/30",
  },
  {
    idx: "02",
    title: "Firebase Firestore Realtime",
    desc: "Lắng nghe và cập nhật dữ liệu 2 chiều không cần reload trang qua Firestore snapshot listeners.",
    color: "text-amber-400",
    bg: "bg-amber-500/15",
    border: "hover:border-amber-500/30",
  },
  {
    idx: "03",
    title: "RunAgents AI (Claude Sonnet CC)",
    desc: "Tích hợp RunAgents model claude-sonnet-cc với khả năng hiểu ngữ cảnh sâu và trích xuất dữ liệu zero-hallucination.",
    color: "text-purple-400",
    bg: "bg-purple-500/15",
    border: "hover:border-purple-500/30",
  },
  {
    idx: "04",
    title: "Astryx Design System",
    desc: "Hệ thống 160+ UI tokens & components chuẩn mực, mang lại trải nghiệm thị giác cao cấp và nhất quán.",
    color: "text-emerald-400",
    bg: "bg-emerald-500/15",
    border: "hover:border-emerald-500/30",
  },
];
